spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: member-service

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_TABLE}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

  cloud:
    # FeignClient url
    openfeign:
      client:
        config:
          performance.url: http://localhost:8000/performance-service/api/performances


#logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
  # Display TraceId and SpanId
  pattern:
    level: "%5p [${spring.application.name:},trace-id : %X{traceId:-}, span-id : %X{spanId:-}]"

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh, info, prometheus, httptrace
  # micrometer Tracing
  tracing:
    sampling:
      probability: 1.0
#    enabled: true
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: proc


