spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: performance-service
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_TABLE}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

  # kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          basicProducer-out-0:
            producer:
              retries: 3 # 재시도 횟수
      bindings:
        basicProducer-out-0:
          destination: performance-info
          content-type: application/json

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh
  # micrometer Tracing
  tracing:
    sampling:
      probability: 1.0
---
spring:
  config:
    activate:
      on-profile: proc

