spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 9999

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: performance-service
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_TABLE}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: proc

