spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:/application.yml
      - classpath:/application-event.yml
      - classpath:/application-domain.yml

  application:
    name: performance-service

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh
  # micrometer Tracing
  tracing:
    sampling:
      probability: 1.0
---
spring:
  config:
    activate:
      on-profile: proc

