package com.sim.event.store.type;

public enum SagaStep {
	INITIATED,
	PAYMENT_REQUEST,
	PAYMENT_COMPLETE,
	PAYMENT_FAILED,
	PAYMENT_ROLLBACK,
	NOTIFICATION_REQUEST,
	NOTIFICATION_COMPLETE,
	RESERVATION_APPLY_ROLLBACK,
	RESERVATION_APPLY_COMPLETE,
	RESERVATION_APPLY_CANCELLED,
	COMPLETE
}
