package com.sim.event.store.type;

public enum SagaStep {
	INITIATED,
	PAYMENT_REQUEST,
	PAYMENT_RESPONSE,
	PAYMENT_ROLLBACK,
	NOTIFICATION_REQUEST,
	NOTIFICATION_RESPONSE,
	RESERVATION_APPLY_ROLLBACK,
	RESERVATION_APPLY_COMPLETE
}
