version: '3.8'
services:
  performance_db:
    image: mysql:8.0
    restart: always
    container_name: performance_db
    ports:
      - "36666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password!
      MYSQL_DATABASE: reservation
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - ./data/mysql-1:/var/lib/mysql
    networks:
      - reservation-networks

  reservation_db:
    image: mysql:8.0
    restart: always
    container_name: reservation_db
    ports:
      - "36667:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password!
      MYSQL_DATABASE: reservation
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - ./data/mysql-2:/var/lib/mysql
    networks:
      - reservation-networks

  payment_db:
    image: mysql:8.0
    restart: always
    container_name: payment_db
    ports:
      - "36668:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password!
      MYSQL_DATABASE: reservation
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - ./data/mysql-3:/var/lib/mysql
    networks:
      - reservation-networks

  member_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: member_db
    ports:
      - "37777:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password!
      POSTGRES_DB: reservation
    volumes:
      - ./data/postgresql-1:/var/lib/postgresql/data
    networks:
      - reservation-networks

  event_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: event_db
    ports:
      - "37778:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password!
      POSTGRES_DB: reservation
    volumes:
      - ./data/postgresql-2:/var/lib/postgresql/data
    networks:
      - reservation-networks

  notification_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: notification_db
    ports:
      - "37779:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password!
      POSTGRES_DB: reservation
    volumes:
      - ./data/postgresql-3:/var/lib/postgresql/data
    networks:
      - reservation-networks

networks:
  reservation-networks:
    driver: bridge
    external: true