spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: paymentRequest;paymentRefund;
      bindings:
        paymentRequest-in-0:
          destination: payment.request
          group: payment.request

        paymentRequest-out-0:
          destination: payment.complete

        paymentRefundRequest-in-0:
          destination: payment-refund-request
          group: payment-refund-event-consumer