spring:
  profiles:
    active:
      - dev

---
server:
  port: 8000

spring:
  config:
    activate:
      on-profile: dev

  application:
    name: gateway-server

  # Gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalLogFilter
          args:
            message: Sring Cloud Gateway Global Log Filter
      routes:
        # Member Service
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        # Performance Service
        - id: performance-service
          uri: lb://PERFORMANCE-SERVICE
          predicates:
            - Path=/performance-service/**
          filters:
            - RewritePath=/performance-service/(?<segment>.*), /$\{segment}

        # Reservation Service
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/**
          filters:
            - RewritePath=/reservation-service/(?<segment>.*), /$\{segment}
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh, gateway, prometheus, httptrace
  endpoint:
    gateway:
      enabled: true

# SpringDoc
springdoc:
  swagger-ui:
    path: /swagger
    urls:
      - name: Reservation-service
        url: http://localhost:8000/reservation-service/api-docs
      - name: Performance-service
        url: http://localhost:8000/performance-service/api-docs
      - name: Member-service
        url: http://localhost:8000/member-service/api-docs