spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: member-service

  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_TABLE}?serverTimezone=Asia/Seoul
    driver-class-name: org.postgresql.Driver
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    # FeignClient url
    openfeign:
      client:
        config:
          performance:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

#logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG

  # Display TraceId and SpanId
  pattern:
    level: "%5p [${spring.application.name:},trace-id : %X{traceId:-}, span-id : %X{spanId:-}]"

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh, info, prometheus, httptrace
  # micrometer tracing
  tracing:
    sampling:
      probability: 1.0
#    enabled: true
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

# Circuit Breaker (Resilience4j)
resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 30s # OPEN -> HALF_OPEN ? ?? ??, default 60s
        slowCallRateThreshold: 80 # slowCall ?? ? ?? ??? ??? ?? ??? ?? ? ???? ???(100)?? ?? ?? ??
        slowCallDurationThreshold: 5s # ?? ?? ??? 5?? slowCall? ???. ?? ?? TimeLimiter? timeoutDuration?? ??? ?
        registerHealthIndicator: true
    instances:
      default:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s # slowCallDurationThreshold??? ?? ????? ?
        cancelRunningFuture: true

---
spring:
  config:
    activate:
      on-profile: proc


