spring:
  profiles:
    active:
      - dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

---
server:
  port: 0

spring:
  config:
    activate:
      on-profile: dev
    import:
      - application.yml
      - application-domain.yml
  application:
    name: member-service

#logging
logging:
  level:
    org:
      springframework:
        web: DEBUG

  # Display TraceId and SpanId
  pattern:
    level: "%5p [${spring.application.name:},trace-id : %X{traceId:-}, span-id : %X{spanId:-}]"

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh, info, prometheus, httptrace
  # micrometer tracing
  tracing:
    sampling:
      probability: 1.0
#    enabled: true
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: proc


