spring:
  profiles:
    active:
      - dev

---
server:
  port: 8000

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: gateway-server

  # Gateway \uC124\uC815
  cloud:
    gateway:
      default-filters:
        - name: GlobalLogFilter
          args:
            message: Sring Cloud Gateway Global Log Filter
      routes:
        # Member Service
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        # Performance Service
        - id: performance-service
          uri: lb://PERFORMANCE-SERVICE
          predicates:
            - Path=/performance-service/**
          filters:
            - RewritePath=/performance-service/(?<segment>.*), /$\{segment}
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

# Eureka \uC124\uC815
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Actuator \uC124\uC815
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, bus, refresh, gateway
  endpoint:
    gateway:
      enabled: true